#!/usr/bin/env bash

declare -A urls

urls=(
    ["mnist_cosine.bin"]="https://drive.google.com/file/d/1vhY_dvn30s_muTN7-vzqKzKSWpRb-YWW/view?usp=sharing"
    ["mnist_euclidean.bin"]="https://drive.google.com/file/d/1SYScDuxFx9-kYpFHljloVuZFZzR7OmBh/view?usp=sharing"
    ["reuters_cosine.bin"]="https://drive.google.com/file/d/1QhLo11NKZ_DpFLNcF33e8sew0K7d7UI4/view?usp=sharing"
    ["reuters_euclidean.bin"]="https://drive.google.com/file/d/1k4WH6piQmHP3c8DixlbmVF99wCF4ysNo/view?usp=sharing"
    ["tng_cosine.bin"]="https://drive.google.com/file/d/1j3O0EIZE3A-eNNy08gFGUK5h86djlOJ-/view?usp=sharing"
    ["tng_euclidean.bin"]="https://drive.google.com/file/d/1KDgp8hnX8hTN4M9APWzOVOWm2qi-aVDl/view?usp=sharing"
)


if [[ "$(python3 --version)" =~ "Python 3" ]]; then
    echo "Python interpreter has been discovered!"
    echo "Version: $(python3 --version)"
    
    if "$(which python3)" -c 'import pkgutil; exit(not pkgutil.find_loader("gdown"))'; then
        echo "gdown found! Version: $(pip3 list | grep gdown | awk '{ print $2 }')"
    else
        echo 'Please install gdown==4.4.0 via pip3!'
    fi
    echo "Check gdown implementation. You can download large files via Python!"
fi


FILE_ID_PATTERN=".*\/d\/([^\/]*)\/.*"

cat <<EOF > confirm.txt
t
EOF

cat <<EOF > cookies.txt
# HTTP cookie file.
# Generated by Wget on 2022-05-11 20:14:38.
# Edit at your own risk.
EOF

for i in "${!urls[@]}"
do
    echo "Downloading $i"

    if [[ ${urls[$i]} =~ $FILE_ID_PATTERN ]]; then
        file_id=${BASH_REMATCH[1]}

        wget --load-cookies cookies.txt -O $i \
            'https://docs.google.com/uc?export=download&id='$file_id'&confirm='$(<confirm.txt)  -q --show-progress

    else
        echo "Cannot match file identifier. Make sure ${urls[$i]} is a valid shareable URL."
    fi

done

rm -i confirm.txt 
rm -i cookies.txt